CREATE DATABASE aula2;

USE aula2;

CREATE TABLE usuario (
	id INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(32) NOT NULL COMMENT 'Inserir sempre com criptografia MD5'
);